

/**
 *
 * Enumeration for serums types.
 *
 */
public enum SerumType {

    HEALING, INVISIBILITY, STRENGTH, HOLY_WATER, POISON, SUPERHUMAN, HULK, DEADPOOL, JACKIECHAN, WOLVERINE, FLASH, MAGNETO,
    MINECRAFT, REGENERATOR, WEAKNESS, CAP, MINDREADER
}